#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 13:41:32 2020

@author: mollybair
"""
import pandas as pd
from pandas_datareader import wb 
import pandas_datareader.data as web
import datetime
import matplotlib.pyplot as plt

## get data from World Bank
# https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#world-bank

def get_wb_data(ids, country, start, end):        
    df_wb = wb.download(indicator = ids, country = country, start = start, end = end)
    return df_wb

## get data from FRED
# https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#fred
def get_fred_data(start, end, cols):
    df_fred = web.DataReader(cols, 'fred', start, end)
    return df_fred

## rename variables for clarity
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
def rename(df, names):
    df.rename(columns = names, inplace = True)
    return df

## merge datasets
def merge(df1, df2, by, method):
    merged = df1.merge(df2, on = by, how = method)
    return merged

## concatenate datasets
def concatenate(dfs):
    df = pd.concat(dfs)
    return df

def single_scatter_plot(df, x, y, xlabel, ylabel, title, save_as):
    fig, ax = plt.subplots()
    ax.scatter(df[x], df[y], color = 'purple')
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    
    plt.xticks(rotation = 45)
    plt.show()
    plt.savefig(save_as)
    
def double_scatter_plot(df, x, y1, y2, xlabel, y1label, y2label, title, save_as):
    fig, ax = plt.subplots()
    ax.scatter(df[x], df[y1], color = 'blue', label = y1label)
    ax.scatter(df[x], df[y2], color = 'green', label = y2label)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    
    plt.xticks(rotation = 45)
    plt.legend()
    plt.show()
    plt.savefig(save_as)
    
def triple_scatter_plot(df, x, y1, y2, y3, xlabel, y1label, y2label, y3label, title, save_as):
    fig, ax = plt.subplots()
    ax.scatter(df[x], df[y1], color = 'blue', label = y1label)
    ax.scatter(df[x], df[y2], color = 'red', label = y2label)
    ax.scatter(df[x], df[y3], color = 'orange', label = y3label)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    
    plt.xticks(rotation = 45)
    plt.legend()
    plt.show()
    plt.savefig(save_as)
    
# https://stackoverflow.com/questions/44863375/how-to-change-spacing-between-ticks-in-matplotlib 
# https://stackoverflow.com/questions/4270301/matplotlib-multiple-datasets-on-the-same-scatter-plot

def main():
    ## get World Bank data and rename variables; convert year to datetime
    ids = ['SP.DYN.TFRT.IN', 'SL.TLF.TOTL.FE.ZS', 'SL.TLF.CACT.FE.ZS', 'SL.TLF.CACT.MA.ZS']
    country = ['US']
    start = 2000
    end = 2020
    df_wb = get_wb_data(ids, country, start, end)
    df_wb = rename(df_wb, {'SP.DYN.TFRT.IN': 'fertility_rate', 'SL.TLF.TOTL.FE.ZS': 'labor_force_female',\
             'SL.TLF.CACT.FE.ZS': 'lfpr_female', 'SL.TLF.CACT.MA.ZS': 'lfpr_male'})
    df_wb = df_wb.reset_index()
    df_wb.drop(columns = ['country'], inplace = True)

    ## get FRED data, add country column, rename variables
    start = datetime.datetime(2000, 1, 1)
    end = datetime.datetime(2020, 5, 31)
    cols = ['LNS11300006', 'LNS11300003', 'LNS11300009']
    df_fred = get_fred_data(start, end, cols)
    df_fred = rename(df_fred, {'LNS11300006': 'lfpr_black', 'LNS11300003': 'lfpr_white', \
                               'LNS11300009': 'lfpr_latino'})
    df_fred = df_fred.reset_index()
    
    ## change FRED date to year 
    year_dict = {}
    for value in df_fred['DATE']:
        year_dict[value] = str(value.year)
    
    df_fred_2 = df_fred
    year = df_fred['DATE'].map(year_dict)
    df_fred_2['DATE'] = year
    df_fred_2 = rename(df_fred_2, {'DATE': 'year'})
    
    ## group fred data by year
    fred_grouped = df_fred.groupby('year').mean()
    
    ## merge World Bank and FRED data
    df = merge(df_wb, fred_grouped, 'year', 'outer')
    print(df.head())
    
    print(single_scatter_plot(df, 'year', 'fertility_rate', 'Year', 'Fertility Rate',\
                              'U.S. Fertility Rate 2000 - 2020', 'fr_year.jpeg'))
    
    print(double_scatter_plot(df, 'year', 'lfpr_male', 'lfpr_female', 'Year', \
                       'Male Labor Force Participation Rate', 'Female Labor Force Participation Rate',\
                       'U.S. Labor Force Participation Rate by Sex 2000 - 2020', 'lfpr_gender_year.jpeg'))
     

    print(triple_scatter_plot(df, 'year', 'lfpr_black', 'lfpr_white', 'lfpr_latino','Year', \
                              'Black Labor Force Participation Rate',\
                                  'White Labor Force Participation Rate', 'Latinx Labor Force Participation Rate',\
                                      'U.S. Labor Force Participation Rate by Race 2000 - 2020',\
                                          'lfpr_race.jpeg'))



